telegram_bot_token: "your_telegram_bot_access_token"
authorized_user: "your_telegram_user_name"
pup: "the_name_of_the_public_utility_provider_pup_you_want_to_notify"
pup_mail: "pup@mail.com"
own_mail: "your@mail.com"
own_mail_nm: "your_name"
own_mail_pw: "your_supersecret_mail_password"
bcc_mail: "bcc@mail.com"
sal_mail: "Sehr geehrte Damen und Herren,\n\nich moechte folgende Information/Auffaelligkeit melden:\n\n"
lea_mail: "\nMit freundlichen Grüßen\nMaxime Mustermann"